title: 김원 포트폴리오
description: Client Programmer </p> 클라이언트 프로그래머
site_title: '@Kim Won Portfolio'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: wonisbest 
email: won990308@naver.com


# absolute or relative
profile_picture: assets/images/profile.jpg

# Google Analytics ID
google_analytics: 
