title: Kim Won Portfolio
description: Client Programmer
site_title: '@Kim Won Portfolio'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: wonisbest 
email: won990308@naver.com


# absolute or relative
profile_picture: assets/images/profile.jpg

# Google Analytics ID
google_analytics: 
